AllCops:
  NewCops: disable
  TargetRubyVersion: 2.6

require:
  - rubocop-rake
  - rubocop-rspec

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false
