AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

require:
  - rubocop-rake
  - rubocop-rspec

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
